services:
  mysql:
    image: mysql:8.0
    #指定容器名称
    container_name: mysql
    restart: always
    #指定服务运行的端口
    ports:
      - "3306:3306"
    #指定容器的环境变量
    environment:
      #数据库密码
      - MYSQL_ROOT_PASSWORD=123456
      #创建的库
      - MYSQL_DATABASE=demo
      #允许多IP连接数据库
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  redis:
    image: redis:7.0
    #指定容器名称
    container_name: redis
    ports:
      - "6379:6379"
  #指定服务名称
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    restart: always
    #指定服务运行的端口
    ports:
      - "8080:8080"
    #依赖的服务
    depends_on:
      - mysql
      - redis