spring:
  application:
    name: scaffold-java
  profiles:
    active: dev

mybatis-plus:
  config-location: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
